### PR TITLE
Updated, improved German Translations

### PR DESCRIPTION
**Pull request by bbak**
## Enhancement or Defect Addressed by This PR
German Translations were improved.

## Description of Proposed Changes
How...

### CODE REVIEW

**Comment by stevencohn** [comment]
Please see this page regarding how to provide corrected language translations. The .resx files are auto-generated by a tool but then overridden by a hints.xml file. Any updates should be specified in that hints file.

There is an existing [German hints file here](https://github.com/stevencohn/OneMore/blob/main/OneMore/Properties/Resources.de-DE-hints.xml)

Please take a look at that file and feel free to submit a PR for changes there

**Review by stevencohn — CHANGES_REQUESTED** [review]
See my previous comment

**Comment by bbak** [comment]
Sorry for the late reply. Ok, got it. Will for sure work on it. Could require some time though.

**Comment by bbak** [comment]
Worked on the right file now. Far from being complete or consistent, but at least a first step. Will keep this branch alive and submit more PRs from time to time.

**Pull request merged**
