### PR TITLE
Add japanese translation

### PR DESCRIPTION
**Pull request by forestail**
## IS YOUR COMMIT SIGNED?
Yes.

## Enhancement or Defect Addressed by This PR
This PR adds Japanese translations. The file 'Resources.ja-JP-hints.xml' was created to ensure the expressions are natural for native Japanese speakers.
This will undoubtedly serve as a motivation for millions of OneNote users in Japan to adopt OneMore.

## Description of Proposed Changes
Please use "ResxTranslator" to reference "Resources.ja-JP-hints.xml" and generate "Resources.ja-JP.resx".

### CODE REVIEW

**Comment by stevencohn** [comment]
When introducing a new language, such as Japanese, it must be created as a Resources.ja-JP.resx, and then only use a hints file to override the necessary customizations. Starting with only a hints file breaks the workflow used to build OneMore.

Whenever new translatable resources are added to OneMore, the [ResxTranslator utility](https://github.com/stevencohn/ResxTranslator) is used to read from and sync with the en-US.resx file to updated all other language .resx files in a controlled manner. The hints files are static overrides so would never get updated when new strings are added, updated, or removed to OneMore. That means ja-JP-hints would almost immediately be out of date and broken on the next release.

Please convert this to a ja-JP.resx file and only create a hints file if necessary. I cannot accept this commit until then.

**Review by stevencohn — CHANGES_REQUESTED** [review]
First, thank you very, very much for doing this! 

When introducing a new language, such as Japanese, it must be created as a Resources.ja-JP.resx, and then only use a hints file to override the necessary customizations. Starting with only a hints file breaks the workflow used to build OneMore.

Whenever new translatable resources are added to OneMore, the [ResxTranslator utility](https://github.com/stevencohn/ResxTranslator) is used to read from and sync with the en-US.resx file to updated all other language .resx files in a controlled manner. The hints files are static overrides so would never get updated when new strings are added, updated, or removed to OneMore. That means ja-JP-hints would almost immediately be out of date and broken on the next release.

Please convert this to a ja-JP.resx file and only create a hints file if necessary. I cannot accept this commit until then.

**Comment by stevencohn** [comment]
@forestail, I can add a base ja-JP file and then put it out for review to create hints where necessary. I'm happy to do that using ResxTranslator since it will automate the whole process quickly. Yes, it uses Google translator and won't be 100% accurate, but it's a better starting place that fits the model.

**Comment by forestail** [comment]
@stevenmcohn Thank you for your comment. Following your advice, I have created the "Resources.ja-JP.resx" file. I have tested OneMore with this file in my environment, and it is working correctly.

**Comment by stevencohn** [comment]
@forestail  Thanks! It is behind, missing a couple of string. But that's OK. I'll patch it up with ResxTranslator. 

I did a random check of about 15 strings and they look good. I'm sure some hints will be needed. But this is a great start. Thank you for helping out.

**Pull request merged**
