### PR TITLE
Improve ger translation

### PR DESCRIPTION
**Pull request by weissm**
## IS YOUR COMMIT SIGNED?
Yes

## Enhancement or Defect Addressed by This PR
Changed very formal and abstract form of "Sie" to more common casual "Du" and adopted grammar accordingly.

## Description of Proposed Changes
Wording more natural now.

### CODE REVIEW

**Review by stevencohn — APPROVED** [review]

**Comment by stevencohn** [comment]
This hasn't been merged yet because these changes cannot be made directly to the Resources.de-DE.resx file. The non-English resx files are auto-generated by my ResxTranslator app. But that app also relies on the Resources.de-DE-hints.xml file. That file contains strings that override the .resx file. Thanks for your patience.

**Comment by weissm** [comment]
Hallo Steven,

 �

Thanks for the information. Was not clear on this dependency. Let me know, if it would help to provide you with an updated Resources.de-DE-hints.xml.

 �

Best regards,

Matthias

 �

**Review by jervin16 — APPROVED** [review]

**Comment by stevencohn** [comment]
Thanks! I'll get it in for the next release

**Review by stevencohn — CHANGES_REQUESTED** [review]
Please adopt my changes from this PR https://github.com/stevencohn/OneMore/pull/962

**Pull request closed without merging**
