### PR TITLE
Update AddIn.cs

### PR DESCRIPTION
**Pull request by weissm**
Removed conversion to bytes, as is should not be needed and acutally crashes add-on: https://learn.microsoft.com/de-de/windows/win32/cimwin32prov/win32-physicalmemoryarray#examples

## IS YOUR COMMIT SIGNED?
Note that this repo requires all commits to be properly signed, [see here](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more info

## Enhancement or Defect Addressed by This PR
What...

## Description of Proposed Changes
How...

### CODE REVIEW

**Comment by stevencohn** [comment]
In precisely what case does it crash?

The code that consumes the output of this method requires bytes so it can then format it as Bytes, KB, MB, or GB. I could just spit out KB but then a 64GB machine would show 640,00,000 KB an that's not very obvious for those looking at this info.

**Comment by weissm** [comment]
In case of the original code, the add-on is not even starting. Not clear on the exact root cause, but it is more but a display flaw.

Still, the conversion to kB increases the original number by 1024, which according to the interface description is not needed. 

As this fix was just recently added, it was assumed to be the root cause.

 �

 �

**Comment by stevencohn** [comment]
So there have been unsolved startup issues for a while. I admit that I am doubtful this has anything to do with the root cause.

Since you are clearly a programmer, it would awesome if you debug your particular issue. The easiest way is to use `System.Diagnostics.Debugger.Launch();` as [described here](https://onemoreaddin.com/developers/Debugging%20OneMore.htm)

That line is already in the Addin() constructor but commented out. Just uncomment it and set a breakpoint. Run it through the VS debugger.

**Comment by JohnMarkHowell** [comment]
Will do!

**Comment by weissm** [comment]
I managed to start the debugger now accordingly and experienced the crash indeed w/ the original *1024 statement enabled here:

Addin.CS, line 70:
			logger.Start(
				$"Starting {process.ProcessName} {process.Id}, {cpu} Mhz, {ram.ToBytes()}, " +
				$"{thread.CurrentCulture.Name}/{thread.CurrentUICulture.Name}, " +
				$"v{AssemblyInfo.Version}, OneNote {Office.GetOneNoteVersion()}, " +
				$"Office {Office.GetOfficeVersion()}, " +
				DateTime.Now.ToString("yyyy-MM-dd HH:mm"));
 
w/ the following error message:

Ausnahme ausgelöst: "System.IndexOutOfRangeException" in River.OneMoreAddIn.dll
Der Thread 0x9e00 hat mit Code 0 (0x0) geendet.

Hope, this helps.

**Comment by stevenmcohn** [comment]
Are you on a 32-bit architecture machine? I don't understand how that math could possibly break. 

If it is in fact breaking there then more code needs to change because the logger statement will not output the correct information; it will think the KB value is a byte value, so 123KB will be reported as 123Bytes.

**Comment by stevencohn** [comment]
Are you on a 32-bit architecture machine? I don't understand how that math could possibly break - or why it's an IndexOutOfRange error, implying there's an index somwehere when it's just math.

If it is in fact breaking there then more code needs to change because the logger statement will not output the correct information; it will think the KB value is a byte value, so 123KB will be reported as 123Bytes.

**Comment by weissm** [comment]
Actually, I am on a 64bit Win11 Lenovo X1 carbon machine using the X64 config. Hence, I debugged the situation a little further. I found my "ram"-number actually depicted a Pentabyte figure. I found that some BIOSes are not properly [maintained ](https://www.dell.com/community/en/conversations/inspiron/inspiron-15-3000-3593-upgradeto-32-gb-ram/647f84d5f4ccf8a8de3bb1b4). Hence I changed the reading to "Capacity" in "Win32_PhysicalMemory". This provides now the proper number in Bytes. Does this address your concern?

**Comment by stevencohn** [comment]
There's still something wrong here. My 16GB laptop is showing up as 8TB.

I'm playing with alternatives, such as this. I'd be interested in hear how this presents on your machine:

```csharp
// Get machine RAM size (Memory size)(using System.Management namespace)
ObjectQuery wmi_obj = new ObjectQuery("SELECT * FROM Win32_OperatingSystem");
ManagementObjectSearcher _findObj = new ManagementObjectSearcher(wmi_obj);
ManagementObjectCollection _ramInfo = _findObj.Get();

foreach (ManagementObject _ram in _ramInfo)
{
	Console.WriteLine(string.Format("Total Visible Memory: {0:0.00} GB\n", (Convert.ToDouble(_ram["TotalVisibleMemorySize"])) / (1024 * 1024)).ToString());
	Console.WriteLine(string.Format("Free Physical Memory: {0:0.00} GB\n", (Convert.ToDouble(_ram["FreePhysicalMemory"])) / (1024 * 1024)).ToString());
	Console.WriteLine(string.Format("Total Virtual Memory Size: {0:0.00} GB\n", (Convert.ToDouble(_ram["TotalVirtualMemorySize"])) / (1024 * 1024)).ToString());
	Console.WriteLine(string.Format("Free Virtual Memory: {0:0.00} GB\n", (Convert.ToDouble(_ram["FreeVirtualMemory"])) / (1024 * 1024)).ToString());
}
```

**Comment by stevencohn** [comment]
Take a look at this commit: https://github.com/stevencohn/OneMore/commit/366cd9c648a52ff3b68c86fe66a356ab4fcbea3b

**Comment by weissm** [comment]
> Take a look at this commit: [366cd9c](https://github.com/stevencohn/OneMore/commit/366cd9c648a52ff3b68c86fe66a356ab4fcbea3b)

Great, worked like a charm. Here is the output you asked for:

01| Starting dllhost 36688, 1201 Mhz, 16 MB, de-DE/de-DE, v5.9.0, OneNote 15.0, Office 16.0, 2023-11-04 19:05
01| ..Total Visible Memory: 15,73 GB

01| ..Free Physical Memory: 1,29 GB

01| ..Total Virtual Memory Size: 43,01 GB

01| ..Free Virtual Memory: 12,03 GB

01| ..Windows 11 Professional, Version 22H2, Build 22621, 64 bit
01| ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.16924.20124)
01| ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
01| ..OneAddInsUpdate(custom[])
01| ..building ribbon
01| ..building ribbon colorizer commands
01| ..building ribbon language proofing commands
01| ..building context menu
01| ..OnStartupComplete(custom[])
01| ..starting command service
01| ..starting reminder service
01| ..starting navigation service
01| ..ready
09| Running command UpdateCommand
03| ..defined 45 hotkeys for input locale 1031

**Comment by stevencohn** [comment]
Good! This seems to work on every case you and I have tried then. So it must work for everyone in the entire world then, right?!

I'll keep my changes and reject this PR. Thank you for your help in debugging the problem. I really appreciate it.

**Pull request closed without merging**
